export const DEAL_STATUS = {
  PENDING: "PENDING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
} as const;

export const DEAL_ESCROW_STATUS = {
  SCHEDULING_PENDING: "SCHEDULING_PENDING",
  CREATIVE_AWAITING_SUBMIT: "CREATIVE_AWAITING_SUBMIT",
  CREATIVE_AWAITING_ADMIN_REVIEW: "CREATIVE_AWAITING_ADMIN_REVIEW",
  PAYMENT_AWAITING: "PAYMENT_AWAITING",
  FUNDS_PENDING: "FUNDS_PENDING",
  FUNDS_CONFIRMED: "FUNDS_CONFIRMED",
  APPROVED_SCHEDULED: "APPROVED_SCHEDULED",
  POSTED_VERIFYING: "POSTED_VERIFYING",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
  REFUNDED: "REFUNDED",
  DISPUTED: "DISPUTED",
} as const;

export const LEGACY_DEAL_STATUS = {
  REQUESTED: "REQUESTED",
  OWNER_ACCEPTED: "OWNER_ACCEPTED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  PAYMENT_CONFIRMING: "PAYMENT_CONFIRMING",
  FUNDS_LOCKED: "FUNDS_LOCKED",
  CREATIVE_DRAFTING: "CREATIVE_DRAFTING",
  CREATIVE_SUBMITTED: "CREATIVE_SUBMITTED",
  CREATIVE_APPROVED: "CREATIVE_APPROVED",
  SCHEDULED: "SCHEDULED",
  POSTED: "POSTED",
  VERIFYING: "VERIFYING",
  RELEASED: "RELEASED",
  REFUNDED: "REFUNDED",
} as const;

export const LEGACY_ESCROW_STATUS = {
  PAYMENT_AWAITING: "PAYMENT_AWAITING",
  PAYMENT_CONFIRMING: "PAYMENT_CONFIRMING",
  FUNDS_LOCKED: "FUNDS_LOCKED",
  RELEASED: "RELEASED",
  REFUNDED: "REFUNDED",
} as const;

export const PREDEAL_STATUS = {
  AWAITING_CREATIVE: "AWAITING_CREATIVE",
  AWAITING_CONFIRMATION: "AWAITING_CONFIRMATION",
  AWAITING_ADMIN_APPROVAL: "AWAITING_ADMIN_APPROVAL",
  READY_FOR_PAYMENT: "READY_FOR_PAYMENT",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  CANCELED: "CANCELED",
} as const;

export type DealStatus = typeof DEAL_STATUS[keyof typeof DEAL_STATUS];
export type DealEscrowStatus = typeof DEAL_ESCROW_STATUS[keyof typeof DEAL_ESCROW_STATUS];
export type LegacyDealStatus = typeof LEGACY_DEAL_STATUS[keyof typeof LEGACY_DEAL_STATUS];
export type LegacyEscrowStatus =
  typeof LEGACY_ESCROW_STATUS[keyof typeof LEGACY_ESCROW_STATUS];
export type PredealStatus = typeof PREDEAL_STATUS[keyof typeof PREDEAL_STATUS];
