import type { MarketplaceChannel } from "@/features/marketplace/types/marketplace";

const today = new Date();
const weekFrom = new Date();
weekFrom.setDate(today.getDate() + 7);

export const mockChannels: MarketplaceChannel[] = [
  {
    id: "1",
    title: "My Crypto Channel",
    username: "mycryptocha",
    avatarUrl: "📰",
    verified: true,
    subscribers: 45_000,
    averageViews: 18_000,
    engagementRate: 40,
    language: "EN",
    priceTon: 2.5,
    description: "Verified creator channel ready for sponsor placements and crypto-native offers.",
    listing: {
      id: "listing-mock-1",
      channelId: "1",
      format: "POST",
      priceTon: 2.5,
      availabilityFrom: today.toISOString(),
      availabilityTo: weekFrom.toISOString(),
      allowEdits: true,
      requiresApproval: true,
      contentRulesText: "Casino and betting promos allowed with approval.",
      tags: ["Casino", "Betting", "iGaming", "Crypto", "English only"],
      isActive: true,
      allowLinkTracking: true,
      allowPinnedPlacement: false,
    },
  },
  {
    id: "ch-flow-1",
    title: "TON Launchpad",
    username: "tonlaunchpad",
    avatarUrl: "🛰️",
    verified: true,
    subscribers: 182_400,
    averageViews: 72_000,
    engagementRate: 38,
    language: "EN",
    priceTon: 4.2,
    description: "Launch announcements and high-intent crypto audience with strong conversion rates.",
    listing: {
      id: "listing-mock-2",
      channelId: "ch-flow-1",
      format: "POST",
      priceTon: 4.2,
      availabilityFrom: today.toISOString(),
      availabilityTo: weekFrom.toISOString(),
      allowEdits: false,
      requiresApproval: true,
      contentRulesText: "Betting partners only. No adult content.",
      tags: ["Betting", "Sports", "Finance", "Promo codes", "No NSFW"],
      isActive: true,
      allowLinkTracking: true,
      allowPinnedPlacement: false,
    },
  },
  {
    id: "ch-flow-2",
    title: "Crypto Atlas",
    username: "cryptoatlas",
    avatarUrl: "🧭",
    verified: true,
    subscribers: 134_900,
    averageViews: 54_500,
    engagementRate: 34,
    language: "EN",
    priceTon: 3.5,
    description: "Daily market maps, token watchlists, and launch alerts for Web3 founders.",
  },
  {
    id: "ch-flow-3",
    title: "Founder Notes",
    username: "foundernotes",
    avatarUrl: "📝",
    verified: true,
    subscribers: 96_200,
    averageViews: 29_400,
    engagementRate: 32,
    language: "EN",
    priceTon: 2.6,
    description: "Product builders, startup advice, and weekly spotlight features.",
  },
  {
    id: "ch-flow-4",
    title: "Signal Stream",
    username: "signalstream",
    avatarUrl: "📡",
    verified: true,
    subscribers: 210_800,
    averageViews: 89_000,
    engagementRate: 41,
    language: "EN",
    priceTon: 5.1,
    description: "High-frequency trading insights with global reach and premium placement slots.",
  },
  {
    id: "ch-flow-5",
    title: "Web3 Horizon",
    username: "web3horizon",
    avatarUrl: "🌅",
    verified: true,
    subscribers: 118_700,
    averageViews: 46_000,
    engagementRate: 29,
    language: "EN",
    priceTon: 3.1,
    description: "Community-first Web3 news with high loyalty and repeat engagement.",
  },
  {
    id: "ch-flow-6",
    title: "Finansy Новости",
    username: "finansy_ru",
    avatarUrl: "💹",
    verified: true,
    subscribers: 165_500,
    averageViews: 63_500,
    engagementRate: 36,
    language: "RU",
    priceTon: 3.8,
    description: "Russian finance digest with premium reach across fintech and crypto segments.",
  },
];
