import type { MarketplaceChannel } from "./types";

export const mockChannels: MarketplaceChannel[] = [
  {
    id: "1",
    title: "My Crypto Channel",
    username: "mycryptocha",
    avatarUrl: "📰",
    verified: true,
    subscribers: 45_000,
    averageViews: 18_000,
    engagementRate: 40,
    language: "EN",
    priceTon: 2.5,
    description: "Verified creator channel ready for sponsor placements and crypto-native offers.",
  },
  {
    id: "ch-flow-1",
    title: "TON Launchpad",
    username: "tonlaunchpad",
    avatarUrl: "🛰️",
    verified: true,
    subscribers: 182_400,
    averageViews: 72_000,
    engagementRate: 38,
    language: "EN",
    priceTon: 4.2,
    description: "Launch announcements and high-intent crypto audience with strong conversion rates.",
  },
  {
    id: "ch-flow-2",
    title: "Crypto Atlas",
    username: "cryptoatlas",
    avatarUrl: "🧭",
    verified: true,
    subscribers: 134_900,
    averageViews: 54_500,
    engagementRate: 34,
    language: "EN",
    priceTon: 3.5,
    description: "Daily market maps, token watchlists, and launch alerts for Web3 founders.",
  },
  {
    id: "ch-flow-3",
    title: "Founder Notes",
    username: "foundernotes",
    avatarUrl: "📝",
    verified: true,
    subscribers: 96_200,
    averageViews: 29_400,
    engagementRate: 32,
    language: "EN",
    priceTon: 2.6,
    description: "Product builders, startup advice, and weekly spotlight features.",
  },
  {
    id: "ch-flow-4",
    title: "Signal Stream",
    username: "signalstream",
    avatarUrl: "📡",
    verified: true,
    subscribers: 210_800,
    averageViews: 89_000,
    engagementRate: 41,
    language: "EN",
    priceTon: 5.1,
    description: "High-frequency trading insights with global reach and premium placement slots.",
  },
  {
    id: "ch-flow-5",
    title: "Web3 Horizon",
    username: "web3horizon",
    avatarUrl: "🌅",
    verified: true,
    subscribers: 118_700,
    averageViews: 46_000,
    engagementRate: 29,
    language: "EN",
    priceTon: 3.1,
    description: "Community-first Web3 news with high loyalty and repeat engagement.",
  },
  {
    id: "ch-flow-6",
    title: "Finansy Новости",
    username: "finansy_ru",
    avatarUrl: "💹",
    verified: true,
    subscribers: 165_500,
    averageViews: 63_500,
    engagementRate: 36,
    language: "RU",
    priceTon: 3.8,
    description: "Russian finance digest with premium reach across fintech and crypto segments.",
  },
];
