export const ROUTES = {
  SPLASH: "/splash",
  MARKETPLACE: "/marketplace",
  MARKETPLACE_CHANNEL_DETAILS: (id: string) => `/marketplace/channels/${id}`,
  MARKETPLACE_CHANNEL_REQUEST: (id: string) => `/marketplace/channels/${id}/request`,
  DEALS: "/deals",
  DEAL_CREATE: (listingId: string) => `/deals/create/${listingId}`,
  DEAL_PREDEAL: (id: string) => `/deals/predeal/${id}`,
  DEAL_DETAILS: (id: string) => `/deals/${id}`,
  ESCROW_BASE: "/escrow",
  ESCROW: (dealId: string) => `/escrow/${dealId}`,
  FUNDS_LOCKED: "/funds-locked",
  CHANNELS: "/channels",
  CHANNEL_PENDING: (id: string) => `/channels/pending/${id}`,
  CHANNEL_DETAILS: (id: string) => `/channels/${id}`,
  PROFILE: "/profile",
  ADD_CHANNEL: "/add-channel",
  ADD_CHANNEL_STEP: (step: string) => `/add-channel/${step}`,
  CHANNEL_MANAGE_BASE: "/channel-manage",
  CHANNEL_MANAGE: (id: string) => `/channel-manage/${id}`,
  CHANNEL_MANAGE_LISTINGS: (id: string) => `/channel-manage/${id}/listings`,
  CHANNEL_MANAGE_LISTINGS_CREATE: (id: string) => `/channel-manage/${id}/listings/create`,
  CHANNEL_MANAGE_LISTINGS_PREVIEW: (id: string) => `/channel-manage/${id}/listings/preview`,
  CHANNEL_MANAGE_LISTINGS_SUCCESS: (id: string) => `/channel-manage/${id}/listings/success`,
  CHANNEL_MANAGE_LISTINGS_EDIT: (id: string, listingId: string) =>
    `/channel-manage/${id}/listings/${listingId}/edit`,
  CHANNEL_MANAGE_SETTINGS: (id: string) => `/channel-manage/${id}/settings`,
  CHANNEL_MANAGE_MODERATORS: (id: string) => `/channel-manage/${id}/moderators`,
} as const;
